### PR TITLE
Feature/update wunderlist api

### LINKED ISSUE #12: Stopped working following update
Hi,
MMM-Wunderlist prompted for an update, which I have done, but now it's stopped working.
Original code is still in config.js with my access token and clinet ID, the list names load but the tasks in the lists dont.
I did get the warnings below when running npm install from the module directory:

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN prefer global marked@0.3.6 should be installed with -g

### PR DESCRIPTION
**Pull request by ArneCL**
Fixes #12 
Fixes issues (Status-Code 500 causes crash) mentioned in  [MM-Forum](https://forum.magicmirror.builders/topic/782/mmm-wunderlist-not-updating)

Changes the deprecated *wunderlistSDK* to a simple API based on *request-promise*.  Eventhough this is not a socket-based solution, it should work fine (as updates are fetched in second-intervalls).
Additionally, this opens up for features of the wunderlist API (like fetching user-avatars..)

### CODE REVIEW

**Comment by paviro** [comment]
Sadly the Pull Request has some merge conflicts. Could you please resolve them?

**Comment by ArneCL** [comment]
While testing, I discovered that even though I updated the fetcher to retrieve the list-revision each interval (and not all todos of the list), the Wunderlist endpoint seems to return a 500 every now and then. I'll add a workaround so the fetcher recovers in this case - which should keep us up and running again... (Please note the WIP = Work in Progress)

Anyways: Also for this Branch Github gives me a green light to merge ...

**Comment by Sispheor** [comment]
So, this module is curently not working until this is merged?

**Comment by ArneCL** [comment]
@Sispheor Yes
@paviro this is ready to merge, and has been successfully tested for about a week
EDIT: Please note that all Tasks will be displayed by creation-date... once this is merged, I'll create a fix for that

**Pull request merged**
